{ DEBUG_NONE, "No debugging"},
{ DEBUG_ERRS, "Verbose error reporting"},
{ DEBUG_INIT, "Debug initialization"},
{ DEBUG_SOCKETS, "Debug socket operations"},
{ DEBUG_PROCESSES, "Debug processes (fork/reap/etc)"},
{ DEBUG_SPIFFY, "Debug the spiffy sending code"},
{ DEBUG_PROCESS_GET, "Debug process_get"},
{ DEBUG_PACKET, "Debug packet"},
{ DEBUG_PROCESS_UDP, "Debug process_udp"},
{ DEBUG_PEER, "Debug process_udp"},
{ DEBUG_LIST, "Debug list"},
{ DEBUG_PARSE, "Debug bt_parse"},
{ DEBUG_CTR, "Debug bt_parse"},
